spring:
  application.name: verify-service
  jpa:
    database: POSTGRESQL
    #show-sql: true
    #hibernate.ddl-auto: validate
    hibernate.default_schema: verify_app
    properties.hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    default-schema: test_app
    change-log: classpath:db_changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=verify_app
    username: postgres
    password: postgres
jwtSecret: bezKoderSecretKey
jwtExpirationMs: 86400000

server:
  port : 8071